baseURL = "https://khoi.io/"
languageCode = "en-us"
title = "khoi.io"
theme = "khoi"
DefaultContentLanguage = "en"

# pygmentsStyle = "dracula"
# pygmentsCodeFences = true
# pygmentsCodefencesGuessSyntax = true

[author]
  name = "khoi"
  homepage = "https://khoi.io/"

[params]
  description = "khoi's random thoughts"
  mainSections = ["post"]
