baseURL = "https://khoi.io/"
languageCode = "en-us"
title = "khoi.io"
theme = "kondo"
DefaultContentLanguage = "en"

[author]
  name = "khoi"
  homepage = "https://khoi.io/"

[params]
  description = "khoi's random thoughts"