version: 2
jobs: 
  build:
    docker:
      - image: cibuilds/hugo
    working_directory: ~/project
    steps:
      - checkout
      - run: git submodule update --init --recursive --remote
      - run: HUGO_ENV=production hugo -t cocoa
      - run: git config --global user.email "khoiracle@gmail.com"
      - run: git config --global user.name "Khoi Lai"
      - add_ssh_keys
      - deploy: 
          command: |
            ./deploy.sh
